"""add_proxy_inventory_table

Revision ID: 2025_11_12_2000
Revises: 2025_11_12_1730
Create Date: 2025-11-12 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_11_12_2000'
down_revision: Union[str, None] = '2025_11_12_1730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False, comment='IP address (IPv4 or IPv6)'),
    sa.Column('port', sa.Integer(), nullable=False, comment='Port number (1-65535)'),
    sa.Column('country', sa.String(length=100), nullable=False, comment='Country'),
    sa.Column('state', sa.String(length=100), nullable=True, comment='State/Region'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('is_available', sa.Boolean(), nullable=False, comment='Is proxy available for purchase'),
    sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=False, comment='Price per hour in USD'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update date'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='Additional notes for admins'),
    sa.PrimaryKeyConstraint('id'),
    comment='Proxy inventory for admin management'
    )
    op.create_index('idx_proxy_inventory_available', 'proxy_inventory', ['is_available'], unique=False)
    op.create_index('idx_proxy_inventory_ip_port', 'proxy_inventory', ['ip', 'port'], unique=True)
    op.create_index('idx_proxy_inventory_location', 'proxy_inventory', ['country', 'state', 'city'], unique=False)
    op.create_index(op.f('ix_proxy_inventory_ip'), 'proxy_inventory', ['ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxy_inventory_ip'), table_name='proxy_inventory')
    op.drop_index('idx_proxy_inventory_location', table_name='proxy_inventory')
    op.drop_index('idx_proxy_inventory_ip_port', table_name='proxy_inventory')
    op.drop_index('idx_proxy_inventory_available', table_name='proxy_inventory')
    op.drop_table('proxy_inventory')
    # ### end Alembic commands ###

