import { User, Coupon, ProxyItem, Language } from './types';
import { Users, DollarSign, ShoppingCart, Activity } from 'lucide-react';

export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

export const TRANSLATIONS = {
  en: {
    adminTitle: 'Proxy Shop Admin',
    dashboard: 'Dashboard',
    users: 'Users',
    coupons: 'Coupons',
    proxies: 'Proxies',
    logout: 'Log out',
    totalUsers: 'Total Users',
    registered: 'Registered in system',
    totalRevenue: 'Total Revenue',
    allTime: 'All time',
    totalPurchases: 'Total Purchases',
    activeProxies: 'Active Proxies',
    notExpired: 'Not expired',
    revenueChart: 'Revenue Chart',
    days7: '7 Days',
    days30: '30 Days',
    searchPlaceholder: 'Search by username, access code...',
    searchProxy: 'Search by IP, country or city...',
    searchCoupon: 'Search by coupon code...',
    createCoupon: 'Create Coupon',
    addProxy: 'Add Proxy',
    bulkUpload: 'Bulk Upload PPTP',
    save: 'Save',
    cancel: 'Cancel',
    upload: 'Upload',
    actions: 'Actions',
    status: 'Status',
    balance: 'Balance',
    ban: 'Ban',
    unban: 'Unban',
    delete: 'Delete',
    active: 'Active',
    blocked: 'Blocked',
    expired: 'Expired',
    available: 'Available',
    sold: 'Sold',
    platform: 'Platform',
    spent: 'Spent',
    purchases: 'Purchases',
    registration: 'Registration',
    code: 'Code',
    discount: 'Discount',
    used: 'Used',
    maxUses: 'Max Uses',
    created: 'Created',
    expiry: 'Expiry',
    ipPort: 'IP:Port',
    country: 'Country',
    region: 'Region',
    price: 'Price',
    type: 'Type',
    modalCreateCoupon: 'Create New Coupon',
    modalAddProxy: 'Add Single Proxy',
    modalBulkProxy: 'Bulk Upload Proxies',
    inputCode: 'Coupon Code',
    inputDiscount: 'Discount (%)',
    inputMaxUses: 'Max usage count',
    inputDate: 'Expiration Date',
    inputIp: 'IP Address',
    inputPort: 'Port',
    inputCountry: 'Country',
    inputCity: 'City/Region',
    inputPrice: 'Price ($)',
    bulkInstructions: 'Supported formats: IP:LOGIN:PASS:COUNTRY:STATE:CITY:ZIP (colon-separated) or CSV',
    noData: 'No data available',
    welcome: 'Welcome to the control panel',
    // New Dashboard Keys
    depositsSum: 'Total Deposits',
    depositsCount: 'Deposits Count',
    pptpSales: 'PPTP Sales',
    proxySales: 'Proxy Sales',
    refundsCount: 'Refunds',
    netProfit: 'Net Profit',
    filterUser: 'Filter by User',
    allUsers: 'All Users',
    periodToday: 'Today',
    periodWeek: 'Week',
    periodMonth: 'Month',
    periodAll: 'All Time',
    financialOverview: 'Financial Overview',
    // Login Page Keys
    loginTitle: 'Admin Authorization',
    loginSubtitle: 'Enter your access code to continue',
    accessCode: 'Access Code',
    loginButton: 'Enter Panel',
    invalidCode: 'Invalid access code. Please try again.',
    loginPlaceholder: 'XXX-XXX-XXX',
    verifying: 'Verifying...',
    accessDenied: 'Access denied. Admin privileges required.',
    showing: 'Showing',
    of: 'of',
    // Broadcast Keys
    broadcast: 'Broadcast',
    broadcastSubtitle: 'Send messages to all users',
    createBroadcast: 'Create Broadcast',
    messageText: 'Message Text',
    messagePhoto: 'Photo URL (optional)',
    filterLanguage: 'Filter by Language',
    allLanguages: 'All Languages',
    russian: 'Russian',
    english: 'English',
    sendTest: 'Send Test',
    sendToAll: 'Send to All',
    broadcastHistory: 'Broadcast History',
    totalUsers: 'Total Users',
    sent: 'Sent',
    failed: 'Failed',
    progress: 'Progress',
    pending: 'Pending',
    running: 'Running',
    completed: 'Completed',
    cancelled: 'Cancelled',
    cancelBroadcast: 'Cancel',
    noHistory: 'No broadcasts yet',
    confirmSend: 'Are you sure you want to send this message to all users?',
    testSent: 'Test message sent to your Telegram',
    broadcastStarted: 'Broadcast started',
  },
  ru: {
    adminTitle: 'Админ-панель Proxy Shop',
    dashboard: 'Панель управления',
    users: 'Пользователи',
    coupons: 'Купоны',
    proxies: 'Прокси',
    logout: 'Выйти',
    totalUsers: 'Всего пользователей',
    registered: 'Зарегистрировано в системе',
    totalRevenue: 'Общий доход',
    allTime: 'За всё время',
    totalPurchases: 'Всего покупок',
    activeProxies: 'Активные прокси',
    notExpired: 'Не истекшие',
    revenueChart: 'График доходов',
    days7: '7 дней',
    days30: '30 дней',
    searchPlaceholder: 'Поиск по username, access code...',
    searchProxy: 'Поиск по IP, стране или городу...',
    searchCoupon: 'Поиск по коду купона...',
    createCoupon: 'Создать купон',
    addProxy: 'Добавить прокси',
    bulkUpload: 'Массовая загрузка PPTP',
    save: 'Создать',
    cancel: 'Отмена',
    upload: 'Загрузить',
    actions: 'Действия',
    status: 'Статус',
    balance: 'Баланс',
    ban: 'Заблокировать',
    unban: 'Разблокировать',
    delete: 'Удалить',
    active: 'Активен',
    blocked: 'Заблокирован',
    expired: 'Истек',
    available: 'Доступен',
    sold: 'Продан',
    platform: 'Платформа',
    spent: 'Потрачено',
    purchases: 'Покупок',
    registration: 'Регистрация',
    code: 'Код',
    discount: 'Скидка',
    used: 'Использовано',
    maxUses: 'Макс. использований',
    created: 'Создан',
    expiry: 'Истекает',
    ipPort: 'IP:Port',
    country: 'Страна',
    region: 'Регион',
    price: 'Цена',
    type: 'Тип',
    modalCreateCoupon: 'Создать купон',
    modalAddProxy: 'Добавить прокси',
    modalBulkProxy: 'Массовая загрузка прокси',
    inputCode: 'Код купона',
    inputDiscount: 'Скидка (%)',
    inputMaxUses: 'Максимальное количество использований',
    inputDate: 'Дата истечения (необязательно)',
    inputIp: 'IP адрес',
    inputPort: 'Порт',
    inputCountry: 'Страна',
    inputCity: 'Город/Регион',
    inputPrice: 'Цена (USD)',
    bulkInstructions: 'Поддерживаемые форматы: IP:LOGIN:PASS:COUNTRY:STATE:CITY:ZIP (через двоеточие) или CSV',
    noData: 'Нет данных',
    welcome: 'Добро пожаловать в админ-панель',
    // New Dashboard Keys
    depositsSum: 'Сумма депозитов',
    depositsCount: 'Количество депозитов',
    pptpSales: 'Сумма покупок PPTP',
    proxySales: 'Сумма покупок прокси',
    refundsCount: 'Количество рефаундов',
    netProfit: 'Чистая прибыль',
    filterUser: 'Фильтр по юзеру',
    allUsers: 'Все пользователи',
    periodToday: 'Сегодня',
    periodWeek: 'Неделя',
    periodMonth: 'Месяц',
    periodAll: 'Всё время',
    financialOverview: 'Финансовый обзор',
    // Login Page Keys
    loginTitle: 'Авторизация администратора',
    loginSubtitle: 'Введите код доступа для продолжения',
    accessCode: 'Код доступа',
    loginButton: 'Войти в панель',
    invalidCode: 'Неверный код доступа. Попробуйте снова.',
    loginPlaceholder: 'XXX-XXX-XXX',
    verifying: 'Проверка...',
    accessDenied: 'Доступ запрещен. Требуются права администратора.',
    showing: 'Показано',
    of: 'из',
    // Broadcast Keys
    broadcast: 'Рассылка',
    broadcastSubtitle: 'Отправка сообщений всем пользователям',
    createBroadcast: 'Создать рассылку',
    messageText: 'Текст сообщения',
    messagePhoto: 'URL фото (опционально)',
    filterLanguage: 'Фильтр по языку',
    allLanguages: 'Все языки',
    russian: 'Русский',
    english: 'Английский',
    sendTest: 'Тест',
    sendToAll: 'Отправить всем',
    broadcastHistory: 'История рассылок',
    totalUsers: 'Всего пользователей',
    sent: 'Отправлено',
    failed: 'Ошибок',
    progress: 'Прогресс',
    pending: 'Ожидание',
    running: 'Отправка',
    completed: 'Завершено',
    cancelled: 'Отменено',
    cancelBroadcast: 'Отменить',
    noHistory: 'Нет рассылок',
    confirmSend: 'Вы уверены, что хотите отправить это сообщение всем пользователям?',
    testSent: 'Тестовое сообщение отправлено в ваш Telegram',
    broadcastStarted: 'Рассылка запущена',
  }
};

export const MOCK_USERS: User[] = [
  { id: 19, accessCode: 'CFY-BY2-7P3', username: 'RezZ0n', platform: 'telegram', balance: 0, spent: 0, purchases: 0, registrationDate: '15 Nov 2025', status: 'active' },
  { id: 18, accessCode: 'D9A-GC4-CX6', username: 'GhostUser', platform: 'web', balance: 15.50, spent: 40.00, purchases: 5, registrationDate: '15 Nov 2025', status: 'active' },
  { id: 17, accessCode: 'XX7-6H2-T4K', username: 'CryptoKing', platform: 'telegram', balance: 100.00, spent: 500.00, purchases: 22, registrationDate: '15 Nov 2025', status: 'active' },
  { id: 16, accessCode: 'LYT-EW5-J9G', username: 'Anon_99', platform: 'web', balance: 0, spent: 0, purchases: 0, registrationDate: '15 Nov 2025', status: 'blocked' },
  { id: 15, accessCode: '68F-6NV-A2H', username: 'ProxyMaster', platform: 'web', balance: 5.00, spent: 12.00, purchases: 2, registrationDate: '15 Nov 2025', status: 'active' },
  { id: 10, accessCode: 'FNU-YYS-LCZ', username: 'abuseadm', platform: 'telegram', balance: 0, spent: 0, purchases: 0, registrationDate: '14 Nov 2025', status: 'active' },
];

export const MOCK_COUPONS: Coupon[] = [
  { id: 1, code: 'SAVE20', discount: 20, used: 15, maxUses: 100, expiry: '2025-12-31', status: 'active' },
  { id: 2, code: 'WELCOME10', discount: 10, used: 542, maxUses: 1000, expiry: '2025-06-01', status: 'active' },
  { id: 3, code: 'BLACKFRIDAY', discount: 50, used: 50, maxUses: 50, expiry: '2024-11-29', status: 'expired' },
];

export const MOCK_PROXIES: ProxyItem[] = [
  { id: 101, ip: '192.168.1.1', port: 1080, country: 'USA', region: 'California', price: 0.05, status: 'available', type: 'SOCKS5', addedAt: '2025-11-18' },
  { id: 102, ip: '45.32.11.89', port: 3128, country: 'Germany', region: 'Frankfurt', price: 0.04, status: 'available', type: 'HTTP', addedAt: '2025-11-18' },
  { id: 103, ip: '88.12.44.122', port: 1080, country: 'UK', region: 'London', price: 0.06, status: 'sold', type: 'SOCKS5', addedAt: '2025-11-17' },
  { id: 104, ip: '103.21.44.1', port: 8080, country: 'Japan', region: 'Tokyo', price: 0.08, status: 'available', type: 'SOCKS5', addedAt: '2025-11-16' },
];